/* Generated by Yosys 0.36+3 (git sha1 a53032104, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module badbranch(num1, num2, sum);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  input [3:0] num1;
  wire [3:0] num1;
  input [3:0] num2;
  wire [3:0] num2;
  output [4:0] sum;
  wire [4:0] sum;
  assign sum[0] = num2[0] ^ num1[0];
  assign _00_ = num2[1] ^ num1[1];
  assign _01_ = ~(num2[0] & num1[0]);
  assign sum[1] = ~(_01_ ^ _00_);
  assign _02_ = ~(num2[2] ^ num1[2]);
  assign _03_ = ~(num2[1] & num1[1]);
  assign _04_ = _00_ & ~(_01_);
  assign _05_ = _04_ | ~(_03_);
  assign sum[2] = ~(_05_ ^ _02_);
  assign _06_ = ~(num2[3] ^ num1[3]);
  assign _07_ = ~(num2[2] & num1[2]);
  assign _08_ = _05_ & ~(_02_);
  assign _09_ = _07_ & ~(_08_);
  assign sum[3] = _09_ ^ _06_;
  assign _10_ = num2[3] & num1[3];
  assign _11_ = ~(_07_ | _06_);
  assign _12_ = _11_ | _10_;
  assign _13_ = _06_ | _02_;
  assign _14_ = _05_ & ~(_13_);
  assign sum[4] = _14_ | _12_;
endmodule

module bug_eval(result);
  wire [3:0] a_num1;
  wire [3:0] a_num2;
  wire [4:0] a_sum;
  wire [3:0] b_num1;
  wire [3:0] b_num2;
  wire [4:0] b_sum;
  wire [2:0] in_shiftandmult;
  output [4:0] result;
  wire [4:0] result;
  wire y1;
  wire y_viv1;
  assign result[0] = y1 ? a_sum[0] : b_sum[0];
  assign result[1] = y1 ? a_sum[1] : b_sum[1];
  assign result[2] = y1 ? a_sum[2] : b_sum[2];
  assign result[3] = y1 ? a_sum[3] : b_sum[3];
  assign result[4] = y1 ? a_sum[4] : b_sum[4];
  badbranch badbranch_instance (
    .num1(4'hx),
    .num2(4'hx),
    .sum(b_sum)
  );
  top_1 eval_top_1 (
    .w(3'h4),
    .y(y1)
  );
  goodbranch goodbranch_instance (
    .num1(4'hx),
    .num2(4'hx),
    .sum(a_sum)
  );
  assign a_num1 = 4'hx;
  assign a_num2 = 4'hx;
  assign b_num1 = 4'hx;
  assign b_num2 = 4'hx;
  assign in_shiftandmult = 3'h4;
  assign y_viv1 = 1'h1;
endmodule

module goodbranch(num1, num2, sum);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  input [3:0] num1;
  wire [3:0] num1;
  input [3:0] num2;
  wire [3:0] num2;
  output [4:0] sum;
  wire [4:0] sum;
  assign _00_ = num2[1] ^ num1[1];
  assign _01_ = ~(num2[0] & num1[0]);
  assign sum[1] = ~(_01_ ^ _00_);
  assign _02_ = ~(num2[2] ^ num1[2]);
  assign _03_ = ~(num2[1] & num1[1]);
  assign _04_ = _00_ & ~(_01_);
  assign _05_ = _04_ | ~(_03_);
  assign sum[2] = ~(_05_ ^ _02_);
  assign _06_ = ~(num2[3] ^ num1[3]);
  assign _07_ = ~(num2[2] & num1[2]);
  assign _08_ = _05_ & ~(_02_);
  assign _09_ = _07_ & ~(_08_);
  assign sum[3] = _09_ ^ _06_;
  assign sum[0] = num2[0] ^ num1[0];
  assign _10_ = num2[3] & num1[3];
  assign _11_ = ~(_07_ | _06_);
  assign _12_ = _11_ | _10_;
  assign _13_ = _06_ | _02_;
  assign _14_ = _05_ & ~(_13_);
  assign sum[4] = _14_ | _12_;
endmodule

module top_1(y, w);
  input [2:0] w;
  wire [2:0] w;
  output y;
  wire y;
  assign y = ~(w[0] | w[1]);
endmodule
