/* Generated by Yosys 0.9+932 (git sha1 UNKNOWN, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module topmsb_1(y, clk, w);
  input clk;
  wire [1:0] i;
  input w;
  output y;
  reg y = 1'h0;
  always @(posedge clk)
      y <= 1'h1;
  assign i = 2'h0;
endmodule
