/* Generated by Yosys 0.8+ (git sha1 UNKNOWN, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module wrongmsb(y, clk, w);
  input clk;
  wire [1:0] i;
  input w;
  output y;
  reg y = 1'h0;
  always @(posedge clk)
      y <= w;
  assign i = 2'h0;
endmodule
