/* Generated by Yosys 0.8+ (git sha1 UNKNOWN, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module top_1(y, w);
  wire _0_;
  input [2:0] w;
  output y;
  assign _0_ = ~(w[1] | w[0]);
  assign y = _0_ & ~(w[2]);
endmodule
